### ISSUE TITLE
Possible hint bug

### ISSUE THREAD

**Issue by tomasfg** [Q42/0hn0#1]
Hi!

Maybe I missed something about the goal / rules of the game, but I think the hint depicted in this screenshot is wrong:

![possible_bug](https://cloud.githubusercontent.com/assets/2552879/6171701/82d334be-b2dc-11e4-9250-e0ab4b3b4480.png)

**Comment by chees** [comment]
No. The one below the 3 has to be blue.
The 3 blue ones can only be above or below it. If you put one above you also need 2 below. If you don't put one above you have to put 3 below.

**Comment by tomasfg** [comment]
Exactly!

I don't know how I missed it :S
