### ISSUE TITLE
Another unsolvable puzzle on Android

### ISSUE THREAD

**Issue by grodin** [Q42/0hn0#6]
![screenshot](http://i.imgur.com/nX0hv0j.png)

I really like the game apart from this fairly rare issue.

**Comment by chees** [comment]
Looks perfectly solvable to me:

![solution](https://cloud.githubusercontent.com/assets/482721/6992710/172b549a-dadb-11e4-913c-b049346919cf.png)

Thanks for the challenge though :)

**Comment by grodin** [comment]
Oops, that's embarrassing! Glad you enjoyed it, at least.
